### ISSUE TITLE
Install dockertoolbox?

### ISSUE THREAD

**Issue by sloria** [IFTTT/dash#10]
Rather than installing docker, docker-compose, docker-machine, and Virtualbox, you can install everything needed for Docker on OSX by installing [docker-toolbox](https://github.com/docker/toolbox). 

There is a homebrew-cask formula (`dockertoolbox`) available.

**Comment by benjamin-smith** [comment]
Toolbox also includes Kitematic, which isn't really part of the Dash workflow. Wouldn't be against installing it, but might not be a good idea ancillary tools.

**Comment by silvamerica** [comment]
@benjamin-smith is correct. We did not want to include Kitematic when it's not necessary for Dash. Additionally, we prefer to be able to upgrade the individual tools independently.
