### ISSUE TITLE
TASK [Add NFS share to /etc/exports] - Fatal error

### ISSUE THREAD

**Issue by RobertPope** [IFTTT/dash#13]
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! privilege output closed while waiting for password prompt:\nBECOME-SUCCESS-nhycxuixfppiinqozwogvknvcwwgupfh\n{\"msg\": \"\", \"invocation\": {\"module_args\": {\"directory_mode\": null, \"force\": null, \"remote_src\": null, \"backrefs\": false, \"insertafter\": null, \"owner\": null, \"follow\": false, \"line\": \"\\\\\\\"/Users\\\\\\\" 192.168.99.100 -alldirs -mapall=0:80\", \"group\": null, \"insertbefore\": null, \"create\": true, \"setype\": null, \"content\": null, \"serole\": null, \"state\": \"present\", \"dest\": \"/etc/exports\", \"selevel\": null, \"regexp\": null, \"validate\": null, \"src\": null, \"seuser\": null, \"delimiter\": null, \"mode\": null, \"backup\": false}}, \"changed\": false, \"backup\": \"\"}\n"}

When installing on El Capitan - the reset of the script seemed to work fine

My etc/exports file contains
Roberts-MacBook-Pro-3:~ robertpope$ cat /etc/exports 
## Begin Dash Developer Environment ##
\"/Users\" 192.168.99.100 -alldirs -mapall=0:80
Roberts-MacBook-Pro-3:~ robertpope$ 

I notice in your script file there's supposed to be and end comment that didn't make it into the file - did it fail here?

Thx

**Comment by RobertPope** [comment]
https://github.com/ansible/ansible/pull/13793

This may be the source of the problem...

**Comment by RobertPope** [comment]
Yeah - it's the extra lines - changed the mac.yml to

- name: Add NFS share to /etc/exports
      lineinfile:
        dest: /etc/exports
        line: "{{ item }}"
        create: yes
      with_items:
        - '"/Users" 192.168.99.100 -alldirs -mapall=0:80'
      become: yes
      become_method: sudo
      register: exports

Got rid of the comments and that seemed to do the trick

**Comment by silvamerica** [comment]
It looks like it was just fixed, so I imagine this will soon no longer apply.

**Comment by santi6291** [comment]
had this issues with ansible 2.x removing the comments worked for me as well

**Comment by onnimonni** [comment]
This is fixed in my PR: https://github.com/IFTTT/dash/pull/18
