### ISSUE TITLE
bootstrap install missing dev-env

### ISSUE THREAD

**Issue by santi6291** [IFTTT/dash#14]
When I run `bash <(curl -fsSL https://raw.githubusercontent.com/IFTTT/dash/master/bin/bootstrap)`
it fails at the following point
```
Installing or Updating Homebrew...
Already up-to-date.



Installing or Updating Ansible...



Checking out Dash repo...
Handing Playbook to Ansible (will require your sudo password)...



/dev/fd/11: line 28: /usr/local/dev-env/bin/dev: No such file or directory
```

**Comment by silvamerica** [comment]
Did the git repo fully checkout at /usr/local/dev-env? That step is silenced to reduce noise. What happens if you run:
`git clone https://github.com/IFTTT/dash.git /usr/local/dev-env`
manually?

**Comment by santi6291** [comment]
A was totally  my bad on a previous failed attempt I deleted content inside and but not the whole directory , leading to the error above since it couldn't create the directory in `/usr/local/dev-env`.
