### ISSUE TITLE
Docker machine ssh command not working

### ISSUE THREAD

**Issue by benjamin-smith** [IFTTT/dash#4]
Running `dev machine ssh dev` fails:

```
SSH cmd error!
command: dev
err    : exit status 127
output : sh: dev: not found
```

Similarly, trying to connect to another machine also fails: `dev machine ssh staging-test`

```
SSH cmd error!
command: dev
err    : exit status 127
output : bash: dev: command not found
```

Running `docker-machine ssh [machine-name]` works as expected.

OSX 10.10.5
Docker version 1.8.3, build f4bf5c7
docker-compose version: 1.4.2
docker-machine version 0.4.1 (HEAD)

**Comment by benjamin-smith** [comment]
Unrelated note: dash is AWESOME. Thanks for releasing!

**Comment by benjamin-smith** [comment]
Looks like it may be all of the `machine` arguments.

Does not work: `dev machine config staging-test`
Works: `docker-machine config staging-test`

I'm assuming this is the same issue.

**Comment by silvamerica** [comment]
Yeah, I think I see the problem in the `dev machine` command alias.
